version: '2.1'

services:
  proxy:
    command: bash -c "./docker-entrypoint.sh && nginx -g 'daemon off;' -c '/nginx-built.conf'"

  db:
    ports:
      - "5432:5432"

  pmp:
    command: node express.js

  dashboard:
    command: node express.js
#
